// <auto-generated />
namespace Nutricionista.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_all : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_all));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301104443_create_all"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
